name: Learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: firts message
        run: |
          echo "Hello World!"
      - name: Fecha actual
        run: date
      - run: ls -l